[server]
port = 8501
address = "0.0.0.0"
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 50

[theme]
primaryColor = "#ffc107"
backgroundColor = "#0b1329"
secondaryBackgroundColor = "#1b263b"
textColor = "#f1f5f9"
font = "sans serif"

[browser]
gatherUsageStats = false
